specifier:
  signatureSpecifications:
    -public
    -static
  annotationSpecifications:
    -Override
  specificationTypes:
    -signatureSpecifications

logypro:
  specificationTypes: test
  package-to-scan: ru.vsu.test
  connectionTypes: OR