specifier:
  signatureSpecifications:
    -public
    -static
  annotationSpecifications:
    -Override
  specificationTypes:
    -signatureSpecifications

logypro:
  package-to-scan: ru.vsu.diplom
  connectionTypes: OR